import { HtmlAdapter } from '../adapters/html.js';
import { InputAdapter } from '../adapters/input.js';
import { VideoAdapter } from '../adapters/video.js';
import { AnimationPlugin } from '../plugins/animation.js';
import { ArchitecturePlugin } from '../plugins/architecture.js';
import { PrototypePlugin } from '../plugins/prototype.js';
import { ResourcePlugin } from '../plugins/resource.js';
import { SourcePlugin } from '../plugins/source.js';
import { StatePlugin } from '../plugins/state.js';

const extensions = quantum.extensions = new Map();
extensions.set('source', SourcePlugin);
extensions.set('html', HtmlAdapter);
extensions.set('input', InputAdapter);
extensions.set('video', VideoAdapter);
extensions.set('animation', AnimationPlugin);
extensions.set('architecture', ArchitecturePlugin);
extensions.set('resource', ResourcePlugin);
extensions.set('prototype', PrototypePlugin);
extensions.set('state', StatePlugin);